@startuml classDiagram
Interface Playable {

}
Interface Commandable
{
    
}

Interface Drawable 
{

}
class DealerCommand
{
    public void execute(Round round, Dealer dealer)   
}
class PlayerCommand
{
    public void execute(Round round, Player player)
}
class Rule
{
    
}
class Turn
Player --|> Playable
User --|> Playable
Dealer --|> Playable
Round o-- Playable

Player --* User
Dealer --* User

Round --|> Drawable
Round --|> Commandable

Player --> PlayerCommand
Dealer --> DealerCommand



@enduml